name: "Test service using Kind"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      
      - name: Deploy Application
        run: |
          kubectl create deployment rock-paper-scissors-app --image=${{ env.REGISTRY }}/${{ github.repository }}:main
          kubectl cluster-info
          kubectl wait pods -n default -l run=rock-paper-scissors-app --for condition=Ready --timeout=90s
          kubectl expose deployment/rock-paper-scissors-app --type=NodePort --port 6000
      
      - name: Test Deployment on Server
        run: |
          kubectl describe services/rock-paper-scissors-app
          kubectl port-forward service/rock-paper-scissors-app 6000:5000 > /dev/null
          ENDPOINT=http://localhost:5000 pytest tests/integration
      
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd-rock-paper-scissors-app
          
